added lock to posture_reminder

diff --git a/dots/.local/bin/posture_reminder b/dots/.local/bin/posture_reminder
--- a/dots/.local/bin/posture_reminder
+++ b/dots/.local/bin/posture_reminder
@@ -1,18 +1,27 @@
 #!/bin/bash
 
-min_sleep_mins=$1
-max_sleep_mins=$2
+(
+  # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 10 seconds
+  flock -x -w 10 200 || exit 1
 
-min_sleep_secs=$((min_sleep_mins * 60))
-max_sleep_secs=$((max_sleep_mins * 60))
+  min_sleep_mins=$1
+  max_sleep_mins=$2
 
-while true; do
-    if [ $max_sleep_secs -ge $min_sleep_secs ]; then
-        [ $max_sleep_secs -eq $min_sleep_secs ] && sleep_duration=$min_sleep_secs || sleep_duration=$(( (RANDOM % (max_sleep_secs - min_sleep_secs)) + min_sleep_secs ))
-        notify-send "Body Awareness" "Shoulders above hips, ears above shoulders"
-        sleep $sleep_duration
-    else
-        echo "Error: max_sleep_secs should be greater than or equal to min_sleep_secs"
-        exit 1
-    fi
-done
+  min_sleep_secs=$((min_sleep_mins * 60))
+  max_sleep_secs=$((max_sleep_mins * 60))
+
+  while true; do
+      if [ $max_sleep_secs -ge $min_sleep_secs ]; then
+          [ $max_sleep_secs -eq $min_sleep_secs ] && sleep_duration=$min_sleep_secs || sleep_duration=$(( (RANDOM % (max_sleep_secs - min_sleep_secs)) + min_sleep_secs ))
+          notify-send "Body Awareness" "Shoulders above hips, ears above shoulders"
+          sleep $sleep_duration
+      else
+          echo "Error: max_sleep_secs should be greater than or equal to min_sleep_secs"
+          exit 1
+      fi
+  done
+
+
+
+
+) 200>/var/lock/.posture_reminder.exclusivelock
